### ISSUE TITLE
A couple of additional suggestions

### ISSUE THREAD

**Issue by kbroman** [cdcrabtree/plotrr#3]
- You might want to put `paper/` in the `.Rbuildignore` file, so that it doesn't get included in the package that's sent to [CRAN](https://cran.r-project.org).

- [CRAN](https://cran.r-project.org) likes to have titles in title case. `R CMD check --as-cran` mentions:

```
The Title field should be in title case, current version then in title case:
‘Making Visual Exploratory Data Analysis with nested Data Easier’
‘Making Visual Exploratory Data Analysis with Nested Data Easier’
```

**Comment by cdcrabtree** [comment]
Fixed. Thanks! Sorry about the small errors. I tried resolving all these before submitting but obviously let some get through.
